/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_jni_api_Demo */

#ifndef _Included_sample_jni_api_Demo
#define _Included_sample_jni_api_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_jni_api_Demo
 * Method:    call
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sample_jni_api_Demo_call
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_api_Demo
 * Method:    invoke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_api_Demo_invoke
  (JNIEnv *, jobject);

/*
 * Class:     sample_jni_api_Demo
 * Method:    error
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_api_Demo_error
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
