/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_jni_logger_Logger */

#ifndef _Included_sample_jni_logger_Logger
#define _Included_sample_jni_logger_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_jni_logger_Logger
 * Method:    verbose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_Logger_verbose
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_Logger
 * Method:    debug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_Logger_debug
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_Logger
 * Method:    info
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_Logger_info
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_Logger
 * Method:    warn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_Logger_warn
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_Logger
 * Method:    error
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_Logger_error
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
