/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_jni_logger_TypeLogger */

#ifndef _Included_sample_jni_logger_TypeLogger
#define _Included_sample_jni_logger_TypeLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_jni_logger_TypeLogger
 * Method:    print
 * Signature: (IFDJZBCLjava/lang/String;Ljava/lang/Integer;Ljava/lang/Float;Ljava/lang/Double;Ljava/lang/Long;Ljava/lang/Boolean;)V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_TypeLogger_print
  (JNIEnv *, jclass, jint, jfloat, jdouble, jlong, jboolean, jbyte, jchar, jstring, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
