/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_jni_demo_Demo */

#ifndef _Included_sample_jni_demo_Demo
#define _Included_sample_jni_demo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_jni_demo_Demo
 * Method:    say
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sample_jni_demo_Demo_say
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
