# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  
  
  # async
  pod 'PromiseKit', '~> 6.8'
  
  # HUD
  pod 'SVProgressHUD'
  
  # theme
  pod 'SwiftTheme'
  
  # json
  pod 'HandyJSON', '~> 5.0.0'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
