/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_jni_logger_SimpleWrapLogger */

#ifndef _Included_sample_jni_logger_SimpleWrapLogger
#define _Included_sample_jni_logger_SimpleWrapLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_jni_logger_SimpleWrapLogger
 * Method:    verbose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_SimpleWrapLogger_verbose
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_SimpleWrapLogger
 * Method:    debug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_SimpleWrapLogger_debug
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_SimpleWrapLogger
 * Method:    info
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_SimpleWrapLogger_info
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_SimpleWrapLogger
 * Method:    warn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_SimpleWrapLogger_warn
  (JNIEnv *, jclass);

/*
 * Class:     sample_jni_logger_SimpleWrapLogger
 * Method:    error
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_jni_logger_SimpleWrapLogger_error
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
